In [2]:
!pip install torch

In [2]:
import torch

In [5]:
t1=torch.tensor(4.)

In [7]:
t1.dtype

torch.float32

In [8]:
# Vector

In [9]:
t2=torch.tensor([1.2,3,4])

In [10]:
t2.dtype

torch.float32

In [11]:
# metrics

In [13]:
t3=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
t3.dtype

torch.int64

In [16]:
t3.shape

torch.Size([3, 3])

# Tensor functions

In [17]:
# create a tensor with a fixed value of for every element

In [39]:
t4=torch.full((3,2),0)

In [40]:
t4

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [44]:
t5=torch.full((3,2),12)

In [45]:
t5

tensor([[12, 12],
        [12, 12],
        [12, 12]])

In [48]:
# concatination
t6=torch.cat((t4,t5))

In [49]:
t6

tensor([[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [12, 12],
        [12, 12],
        [12, 12]])

In [50]:
# change the sin of each element

In [51]:
t7=torch.sin((t6))

In [52]:
t7

tensor([[ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [-0.5366, -0.5366],
        [-0.5366, -0.5366],
        [-0.5366, -0.5366]])

In [53]:
# change the shape of tensor

In [57]:
t8=t6.reshape((2,2,3))

In [58]:
t8

tensor([[[ 0,  0,  0],
         [ 0,  0,  0]],

        [[12, 12, 12],
         [12, 12, 12]]])