# Linear regression from scratch using Pytorch

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
#Making training data
# Input --> (temperature,rainfall,humidity)---> Yield  of apple and oranges crop

In [ ]:
inputs=np.array([
    [56,70,45],
    [44,56,56],
    [34,54,56],
    [78,67,67],
    [34,76,56]

],dtype='float32')

In [ ]:
# target - (apples,oranges)
target=np.array([
    [23,45] ,
    [45,65],
    [67,43],
    [23,32],
    [12,21]
],dtype='float32')

In [ ]:
# convert inputs and target to tensors
inputs=torch.from_numpy(inputs)
target=torch.from_numpy(target)
print(inputs)
print(target)

tensor([[56., 70., 45.],
        [44., 56., 56.],
        [34., 54., 56.],
        [78., 67., 67.],
        [34., 76., 56.]])
tensor([[23., 45.],
        [45., 65.],
        [67., 43.],
        [23., 32.],
        [12., 21.]])


In [ ]:
# weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.7506, -0.6299, -1.1776],
        [-1.0079, -0.8620,  0.7277]], requires_grad=True)
tensor([-0.2533, -0.2154], requires_grad=True)


In [ ]:
# define the model
def model(x):
  return x @ w.t()+b

In [ ]:
# predictions
preds=model(inputs)
print(preds)

tensor([[-55.3038, -84.2543],
        [-68.4453, -52.0861],
        [-74.6914, -40.2827],
        [-62.8073, -87.8332],
        [-88.5495, -59.2472]], grad_fn=<AddBackward0>)


In [ ]:
# loss function - mse  (mean_squared_error )
from sklearn.metrics import mean_squared_error

In [ ]:

def MSE(actual,predicted):

   diff = torch.mean((actual - predicted)**2)
   return diff

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# print loss
loss=MSE(target,preds)
print(loss)

tensor(11470.2305, grad_fn=<MeanBackward0>)


In [ ]:
# compute gradient
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.7506, -0.6299, -1.1776],
        [-1.0079, -0.8620,  0.7277]], requires_grad=True)
tensor([[-4861.1533, -6575.2778, -5838.2378],
        [-5459.4062, -6845.8989, -5911.9521]])


In [ ]:
print(b)
print(b.grad)

tensor([-0.2533, -0.2154], requires_grad=True)
tensor([-207.9189, -211.8814])


In [ ]:
# reset gradient
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
# adjust weight and grads
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[ 0.7506, -0.6299, -1.1776],
        [-1.0079, -0.8620,  0.7277]], requires_grad=True)
tensor([-0.2533, -0.2154], requires_grad=True)


In [ ]:
# training for multiple  epochs
for i in range(400):
  preds=model(inputs)
  loss=MSE(target,preds)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()
  print(f"Epochs{i} and loss {loss}")

Epochs0 and loss 313.94329833984375
Epochs1 and loss 313.88751220703125
Epochs2 and loss 313.8318176269531
Epochs3 and loss 313.7761535644531
Epochs4 and loss 313.7205505371094
Epochs5 and loss 313.66510009765625
Epochs6 and loss 313.60968017578125
Epochs7 and loss 313.55438232421875
Epochs8 and loss 313.4991149902344
Epochs9 and loss 313.44403076171875
Epochs10 and loss 313.388916015625
Epochs11 and loss 313.3338317871094
Epochs12 and loss 313.2789611816406
Epochs13 and loss 313.22406005859375
Epochs14 and loss 313.1693420410156
Epochs15 and loss 313.1146545410156
Epochs16 and loss 313.05999755859375
Epochs17 and loss 313.0054626464844
Epochs18 and loss 312.9510192871094
Epochs19 and loss 312.8966369628906
Epochs20 and loss 312.84234619140625
Epochs21 and loss 312.78814697265625
Epochs22 and loss 312.73394775390625
Epochs23 and loss 312.679931640625
Epochs24 and loss 312.62591552734375
Epochs25 and loss 312.572021484375
Epochs26 and loss 312.5181579589844
Epochs27 and loss 312.4644165

In [ ]:
preds=model(inputs)

In [ ]:
preds

tensor([[17.4001, 28.3907],
        [35.8373, 41.7625],
        [39.0255, 42.3206],
        [35.9931, 49.5541],
        [33.9906, 38.1261]], grad_fn=<AddBackward0>)

In [ ]:
target

tensor([[23., 45.],
        [45., 65.],
        [67., 43.],
        [23., 32.],
        [12., 21.]])

In [ ]:
loss=MSE(target,preds)
print(loss)

tensor(296.8057, grad_fn=<MeanBackward0>)
